(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e=this||self;function f(b,c){b=b.split(".");var a=e;b[0]in a||"undefined"==typeof a.execScript||a.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)b.length||void 0===c?a[d]&&a[d]!==Object.prototype[d]?a=a[d]:a=a[d]={}:a[d]=c}
;var g={YEAR_FULL:"y",YEAR_FULL_WITH_ERA:"y G",YEAR_MONTH_ABBR:"MMM y",YEAR_MONTH_FULL:"MMMM y",YEAR_MONTH_SHORT:"MM/y",MONTH_DAY_ABBR:"MMM d",MONTH_DAY_FULL:"MMMM dd",MONTH_DAY_SHORT:"M/d",MONTH_DAY_MEDIUM:"MMMM d",MONTH_DAY_YEAR_MEDIUM:"MMM d, y",WEEKDAY_MONTH_DAY_MEDIUM:"EEE, MMM d",WEEKDAY_MONTH_DAY_YEAR_MEDIUM:"EEE, MMM d, y",DAY_ABBR:"d",MONTH_DAY_TIME_ZONE_SHORT:"MMM d, h:mm\u202fa zzzz"};
g={YEAR_FULL:"y",YEAR_FULL_WITH_ERA:"y G",YEAR_MONTH_ABBR:"MMM 'de' y",YEAR_MONTH_FULL:"MMMM 'de' y",YEAR_MONTH_SHORT:"MM/y",MONTH_DAY_ABBR:"d 'de' MMM",MONTH_DAY_FULL:"dd 'de' MMMM",MONTH_DAY_SHORT:"dd/MM",MONTH_DAY_MEDIUM:"d 'de' MMMM",MONTH_DAY_YEAR_MEDIUM:"d 'de' MMM 'de' y",WEEKDAY_MONTH_DAY_MEDIUM:"EEE, d 'de' MMM",WEEKDAY_MONTH_DAY_YEAR_MEDIUM:"EEE, d 'de' MMM 'de' y",DAY_ABBR:"d",MONTH_DAY_TIME_ZONE_SHORT:"d 'de' MMM, HH:mm zzzz"};var h={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
h={ERAS:["a.C.","d.C."],ERANAMES:["antes de Cristo","depois de Cristo"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),STANDALONEMONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),SHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),STANDALONESHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),
WEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),STANDALONEWEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),SHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),STANDALONESHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),NARROWWEEKDAYS:"DSTQQSS".split(""),STANDALONENARROWWEEKDAYS:"DSTQQSS".split(""),SHORTQUARTERS:["T1","T2","T3","T4"],QUARTERS:["1\u00ba trimestre",
"2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, d 'de' MMMM 'de' y","d 'de' MMMM 'de' y","d 'de' MMM 'de' y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} '\u00e0s' {0}","{1} '\u00e0s' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};function k(b,c){if(void 0===c){c=b+"";var a=c.indexOf(".");c=Math.min(-1===a?0:c.length-a-1,3)}a=Math.pow(10,c);return{g:c,f:(b*a|0)%a}}
function l(b,c){c=k(b,c);return 1==(b|0)&&0==c.g?"one":"other"}
l=function(b,c){var a=b|0;b=k(b,c);return 0<=a&&1>=a?"one":0!=a&&0==a%1E6&&0==b.g?"many":"other"};f("YT_I18N_FORMATTING_GOOG_LOCALE","pt-BR");f("YT_I18N_FORMATTING_DATE_TIME_PATTERNS",g);f("YT_I18N_FORMATTING_DATE_TIME_SYMBOLS",h);
f("YT_I18N_FORMATTING_RELATIVE_DATE_TIME_SYMBOLS",{DAY:{LONG:{R:{"-1":"ontem","-2":"anteontem",0:"hoje",1:"amanh\u00e3",2:"depois de amanh\u00e3"},P:"one{h\u00e1 # dia}other{h\u00e1 # dias}",F:"one{em # dia}other{em # dias}"}},HOUR:{LONG:{R:{0:"esta hora"},P:"one{h\u00e1 # hora}other{h\u00e1 # horas}",F:"one{em # hora}other{em # horas}"},SHORT:{R:{0:"esta hora"},P:"one{h\u00e1 # h}other{h\u00e1 # h}",F:"one{em # h}other{em # h}"}},MINUTE:{LONG:{R:{0:"este minuto"},P:"one{h\u00e1 # minuto}other{h\u00e1 # minutos}",
F:"one{em # minuto}other{em # minutos}"},SHORT:{R:{0:"este minuto"},P:"one{h\u00e1 # min.}other{h\u00e1 # min.}",F:"one{em # min.}other{em # min.}"}},MONTH:{LONG:{R:{"-1":"m\u00eas passado",0:"este m\u00eas",1:"pr\u00f3ximo m\u00eas"},P:"one{h\u00e1 # m\u00eas}other{h\u00e1 # meses}",F:"one{em # m\u00eas}other{em # meses}"}},QUARTER:{LONG:{R:{"-1":"\u00faltimo trimestre",0:"este trimestre",1:"pr\u00f3ximo trimestre"},P:"one{h\u00e1 # trimestre}other{h\u00e1 # trimestres}",F:"one{em # trimestre}other{em # trimestres}"},
SHORT:{R:{"-1":"\u00faltimo trimestre",0:"este trimestre",1:"pr\u00f3ximo trimestre"},P:"one{h\u00e1 # trim.}other{h\u00e1 # trim.}",F:"one{em # trim.}other{em # trim.}"}},SECOND:{LONG:{R:{0:"agora"},P:"one{h\u00e1 # segundo}other{h\u00e1 # segundos}",F:"one{em # segundo}other{em # segundos}"},SHORT:{R:{0:"agora"},P:"one{h\u00e1 # seg.}other{h\u00e1 # seg.}",F:"one{em # seg.}other{em # seg.}"}},WEEK:{LONG:{R:{"-1":"semana passada",0:"esta semana",1:"pr\u00f3xima semana"},P:"one{h\u00e1 # semana}other{h\u00e1 # semanas}",
F:"one{em # semana}other{em # semanas}"},SHORT:{R:{"-1":"semana passada",0:"esta semana",1:"pr\u00f3xima semana"},P:"one{h\u00e1 # sem.}other{h\u00e1 # sem.}",F:"one{em # sem.}other{em # sem.}"}},YEAR:{LONG:{R:{"-1":"ano passado",0:"este ano",1:"pr\u00f3ximo ano"},P:"one{h\u00e1 # ano}other{h\u00e1 # anos}",F:"one{em # ano}other{em # anos}"}}});f("YT_I18N_FORMATTING_PLURAL_RULES_SELECT",l);
f("YT_I18N_FORMATTING_DURATION_TIME_SYMBOLS",{DAY:{LONG:"one{# dia}other{# dias}",SHORT:"one{# dia}other{# dias}",NARROW:"one{# dia}other{# dias}"},HOUR:{LONG:"one{# hora}other{# horas}",SHORT:"one{# h}other{# h}",NARROW:"one{# h}other{# h}"},MINUTE:{LONG:"one{# minuto}other{# minutos}",SHORT:"one{# min}other{# min}",NARROW:"one{# min}other{# min}"},MONTH:{LONG:"one{# m\u00eas}other{# meses}",SHORT:"one{# m\u00eas}other{# meses}",NARROW:"one{# m\u00eas}other{# meses}"},SECOND:{LONG:"one{# segundo}other{# segundos}",
SHORT:"one{# s}other{# s}",NARROW:"one{# s}other{# s}"},WEEK:{LONG:"one{# semana}other{# semanas}",SHORT:"one{# sem.}other{# sem.}",NARROW:"one{# sem.}other{# sem.}"},YEAR:{LONG:"one{# ano}other{# anos}",SHORT:"one{# ano}other{# anos}",NARROW:"one{# ano}other{# anos}"}});}).call(this);
